### ISSUE TITLE
ml-grid-docs sources

### ISSUE THREAD

**Issue by ognone** [developmentseed/ml-hv-grid-pub#3]
@wronk Dear Matt,

where are the sources for http://devseed.com/ml-grid-docs/ ?

https://devseed.com/ml-grid-docs/assets/graphics/content/results_plots/ tells me it must be somewhere at Github.

I'm one of OSM's power line [mappers](https://wiki.openstreetmap.org/wiki/Category:Power_user) and have been involved into your Pakistan HV effort (unaffiliated).

Kind regards

**Comment by olafveerman** [comment]
@ognone You can find the repo here: https://github.com/developmentseed/ml-grid-docs
Thanks for mapping the grid!
